// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sample.IdentityManagement.GraphQL.Entities.Context;

namespace Sample.IdentityManagement.GraphQL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sample.IdentityManagement.GraphQL.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d51b03c-27af-4209-84ab-be7bd5ca5c08"),
                            Description = "Cash account for our users",
                            OwnerId = new Guid("ae780b6d-69b8-4c75-8274-436e64738ee8"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("e6394d57-4f5a-4aca-933f-4782d0c6b47e"),
                            Description = "Savings account for our users",
                            OwnerId = new Guid("fdfb7dfa-c283-4a13-bab9-1c81c76f2b3f"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("cbe28d98-2b81-4c78-8169-0e36a7652fa0"),
                            Description = "Income account for our users",
                            OwnerId = new Guid("fdfb7dfa-c283-4a13-bab9-1c81c76f2b3f"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("Sample.IdentityManagement.GraphQL.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae780b6d-69b8-4c75-8274-436e64738ee8"),
                            Address = "John Doe's address",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("fdfb7dfa-c283-4a13-bab9-1c81c76f2b3f"),
                            Address = "Jane Doe's address",
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("Sample.IdentityManagement.GraphQL.Entities.Account", b =>
                {
                    b.HasOne("Sample.IdentityManagement.GraphQL.Entities.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Sample.IdentityManagement.GraphQL.Entities.Owner", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
